BaseUrl= "https://tyayers.github.io/api-team-principles/"
LanguageCode= "en-US"
Title= "7 API Team Principles"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2019"
canonifyurls = true

[author]
  name = "syui"

[params]
  description = "(api||die)"
  cover = "images/network.png"
  author = "syui"
  authorlocation = ""
  authorwebsite = "https://syui.github.io/hugo-theme-air"
  bio= "my bio"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
  # logo = "images/network.png"
